### ISSUE TITLE
No module named 'requests' when running "export --html2pdf"

### ISSUE THREAD

**Issue by Timotheous** [strictdoc-project/strictdoc#1701] opened 2024-03-12 22:17 UTC
I am using a Python 3.8.4 virtual environment on Win10 Enterprise Version 22H2, OS Build 19045.4046. 
As per the ZephyrProject getting started guide.  ZephyrProject compiles.

ZephyrProject repo is cloned at %HOMEPATH%\ZephyrProject.
Requirements documents repo is cloned at %HOMEPATH%\ZephyrProject\reqmgmt.

strictdoc export Docs/ --output-dir TestThree works.  
It leaves the html file at %HOMEPATH%\ZephyrProject\reqmgmt\TestThree\

strictdoc export docs/ --formats=html2pdf --output-dir TestFour does create the html files.
But fails to create the pdf file.  Here is the console readout:

(.venv) C:\Users\twilcox\zephyrproject\reqmgmt>strictdoc export docs/ --formats=html2pdf --output-dir TestFour
Parallelization: Enabled
Step 'Parse SDoc project tree' start.
Step 'Find and read SDoc files' start.
Reading SDOC: zephyr_01_high_level_requirements.sdoc ........ 0.08s
Reading SDOC: zephyr_02_functional_requirements.sdoc ........ 0.15s
Step 'Find and read SDoc files' took: 0.5 sec.
Step 'Build traceability graph' start.
Step 'Build traceability graph' took: 0.01 sec.
Step 'Parse SDoc project tree' took: 0.59 sec.
Step 'Export SDoc' start.
Compile Jinja templates ..................................... 0.77s
Copying StrictDoc's assets for HTML2PDF: 40 files.
Generating printable HTML document .......................... 0.39s
Generating printable HTML document .......................... 0.97s
Traceback (most recent call last):
  File "c:\users\twilcox\zephyrproject\.venv\lib\site-packages\strictdoc\export\html2pdf\html2pdf.py", line 12, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
PDFPrintDriver: printing HTML to PDF using HTML2PDF and Chrome Driver . 0.09s
Step 'Export SDoc' took: 2.32 sec.

I have uninstalled and installed the module without errors.

**Comment by stanislaw** [comment] 2024-03-13 19:21
Thanks a lot for reporting this. To my best knowledge, this issue should not be happening because the webdriver_manager dependency does include `requests` here: https://github.com/SergeyPirogov/webdriver_manager/blob/master/setup.py#L49.

I will anyway include the `requests` library directly to StrictDoc's list of dependencies to see if this improves things. For now, could you tell me which output you get in your environment if you run `pip install requests`?

**Comment by Timotheous** [comment] 2024-03-13 19:50
Here is the output starting with activating the environment.
I have reinstalled or upgraded the module several times.
I have tried several command syntax, including copying from the user guide.
The result is essentially the same.  I get the html output and the file structure for the pdf. But not the pdf file.

Hope you can spot something.


C:\Users\twilcox>cmd.exe /K "zephyrproject\.venv\Scripts\activate.bat & cd zephyrproject"

(.venv) C:\Users\twilcox\zephyrproject>pip install requests
Requirement already satisfied: requests in c:\users\twilcox\zephyrproject\.venv\lib\site-packages (2.31.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\twilcox\zephyrproject\.venv\lib\site-packages (from requests) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\twilcox\zephyrproject\.venv\lib\site-packages (from requests) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\twilcox\zephyrproject\.venv\lib\site-packages (from requests) (2.2.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\twilcox\zephyrproject\.venv\lib\site-packages (from requests) (2024.2.2)

(.venv) C:\Users\twilcox\zephyrproject>strictdoc export reqmgmt\docs\ --formats=html2pdf --output-dir reqmgmt\output
Parallelization: Enabled
Step 'Parse SDoc project tree' start.
Step 'Find and read SDoc files' start.
Reading SDOC: zephyr_02_functional_requirements.sdoc ........ 0.01s
Reading SDOC: zephyr_01_high_level_requirements.sdoc ........ 0.00s
Step 'Find and read SDoc files' took: 0.42 sec.
Step 'Build traceability graph' start.
Step 'Build traceability graph' took: 0.01 sec.
Step 'Parse SDoc project tree' took: 0.56 sec.
Step 'Export SDoc' start.
Copying StrictDoc's assets for HTML2PDF: 40 files (40 files skipped as non-modified).
Generating printable HTML document .......................... 0.05s
Generating printable HTML document .......................... 0.12s
Traceback (most recent call last):
  File "c:\users\twilcox\zephyrproject\.venv\lib\site-packages\strictdoc\export\html2pdf\html2pdf.py", line 8, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
PDFPrintDriver: printing HTML to PDF using HTML2PDF and Chrome Driver . 0.09s
Step 'Export SDoc' took: 0.29 sec.

(.venv) C:\Users\twilcox\zephyrproject>cd reqmgmt

(.venv) C:\Users\twilcox\zephyrproject\reqmgmt>strictdoc export docs\ --formats=html2pdf --output-dir output_1
Parallelization: Enabled
Step 'Parse SDoc project tree' start.
Step 'Find and read SDoc files' start.
Reading SDOC: zephyr_01_high_level_requirements.sdoc ........ 0.08s
Reading SDOC: zephyr_02_functional_requirements.sdoc ........ 0.15s
Step 'Find and read SDoc files' took: 0.51 sec.
Step 'Build traceability graph' start.
Step 'Build traceability graph' took: 0.01 sec.
Step 'Parse SDoc project tree' took: 0.63 sec.
Step 'Export SDoc' start.
Compile Jinja templates ..................................... 0.85s
Copying StrictDoc's assets for HTML2PDF: 40 files.
Generating printable HTML document .......................... 0.41s
Generating printable HTML document .......................... 1.01s
Traceback (most recent call last):
  File "c:\users\twilcox\zephyrproject\.venv\lib\site-packages\strictdoc\export\html2pdf\html2pdf.py", line 8, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
PDFPrintDriver: printing HTML to PDF using HTML2PDF and Chrome Driver . 0.09s
Step 'Export SDoc' took: 2.49 sec.

(.venv) C:\Users\twilcox\zephyrproject\reqmgmt>

**Comment by stanislaw** [comment] 2024-03-13 20:11
Could you reinstall strictdoc using `pip install strictdoc --pre` and let me know if it changes anything for you? 

Note that HTML2PDF has been released only recently and the UI part of it is hidden under a feature toggle. The fact that it is available on the command-line interface (CLI) is due to the fact that I haven't found a good way to hide the CLI option under the same feature toggle 😃 

I have also updated the doc a little bit: https://github.com/strictdoc-project/strictdoc/pull/1702/files.

**Comment by Timotheous** [comment] 2024-03-13 20:20
_(.venv) C:\Users\twilcox\zephyrproject>pip install strictdoc --pre_

resulted in a long list of 
_Requirement already satisfied: ..._

Including 
_Requirement already satisfied: requests in c:\users\twilcox\zephyrproject\.venv\lib\site-packages (from webdriver-manager->strictdoc) (2.31.0)_

Export command was essentially the same:
_(.venv) C:\Users\twilcox\zephyrproject\reqmgmt>strictdoc export docs\ --formats=html2pdf --output-dir output_1
Parallelization: Enabled
Step 'Parse SDoc project tree' start.
Step 'Find and read SDoc files' start.
Reading SDOC: zephyr_01_high_level_requirements.sdoc ........ 0.00s
Reading SDOC: zephyr_02_functional_requirements.sdoc ........ 0.01s
Step 'Find and read SDoc files' took: 0.35 sec.
Step 'Build traceability graph' start.
Step 'Build traceability graph' took: 0.01 sec.
Step 'Parse SDoc project tree' took: 0.47 sec.
Step 'Export SDoc' start.
Copying StrictDoc's assets for HTML2PDF: 40 files.
Generating printable HTML document .......................... 0.04s
Generating printable HTML document .......................... 0.11s
Traceback (most recent call last):
  File "c:\users\twilcox\zephyrproject\.venv\lib\site-packages\strictdoc\export\html2pdf\html2pdf.py", line 8, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
PDFPrintDriver: printing HTML to PDF using HTML2PDF and Chrome Driver . 0.09s
Step 'Export SDoc' took: 0.34 sec._

**Comment by Timotheous** [comment] 2024-03-13 20:21
Here is the entire install response for reference:

_(.venv) C:\Users\twilcox\zephyrproject>pip install strictdoc --pre
Requirement already satisfied: strictdoc in c:\users\twilcox\zephyrproject\.venv\lib\site-packages (0.0.49)
Requirement already satisfied: beautifulsoup4==4.*,>=4.12.0 in c:\users\twilcox\zephyrproject\.venv\lib\site-packages (from strictdoc) (4.12.3)
Requirement already satisfied: docutils==0.*,>=0.16 in c:\users\twilcox\zephyrproject\.venv\lib\site-packages (from strictdoc) (0.20.1)
Requirement already satisfied: fastapi>=0.83.0 in c:\users\twilcox\zephyrproject\.venv\lib\site-packages (from strictdoc) (0.110.0)
Requirement already satisfied: graphviz>=0.20.1 in c:\users\twilcox\zephyrproject\.venv\lib\site-packages (from strictdoc) (0.20.1)
Requirement already satisfied: html5lib>=1.1 in c:\users\twilcox\zephyrproject\.venv\lib\site-packages (from strictdoc) (1.1)
Requirement already satisfied: jinja2>=2.11.2 in c:\users\twilcox\zephyrproject\.venv\lib\site-packages (from strictdoc) (3.1.3)
Requirement already satisfied: lxml==4.*,>=4.6.2 in c:\users\twilcox\zephyrproject\.venv\lib\site-packages (from strictdoc) (4.9.4)
Requirement already satisfied: pybtex==0.*,>=0.23.0 in c:\users\twilcox\zephyrproject\.venv\lib\site-packages (from strictdoc) (0.24.0)
Requirement already satisfied: pygments==2.*,>=2.10.0 in c:\users\twilcox\zephyrproject\.venv\lib\site-packages (from strictdoc) (2.17.2)
Requirement already satisfied: python-datauri==0.*,>=0.2.9 in c:\users\twilcox\zephyrproject\.venv\lib\site-packages (from strictdoc) (0.2.9)
Requirement already satisfied: python-multipart in c:\users\twilcox\zephyrproject\.venv\lib\site-packages (from strictdoc) (0.0.9)
Requirement already satisfied: reqif==0.*,>=0.0.39 in c:\users\twilcox\zephyrproject\.venv\lib\site-packages (from strictdoc) (0.0.41)
Requirement already satisfied: selenium in c:\users\twilcox\zephyrproject\.venv\lib\site-packages (from strictdoc) (4.18.1)
Requirement already satisfied: setuptools in c:\users\twilcox\zephyrproject\.venv\lib\site-packages (from strictdoc) (47.1.0)
Requirement already satisfied: spdx-tools in c:\users\twilcox\zephyrproject\.venv\lib\site-packages (from strictdoc) (0.8.2)
Requirement already satisfied: textx==3.*,>=3.0.0 in c:\users\twilcox\zephyrproject\.venv\lib\site-packages (from strictdoc) (3.1.1)
Requirement already satisfied: toml in c:\users\twilcox\zephyrproject\.venv\lib\site-packages (from strictdoc) (0.10.2)
Requirement already satisfied: uvicorn>=0.14.0 in c:\users\twilcox\zephyrproject\.venv\lib\site-packages (from uvicorn[standard]>=0.14.0->strictdoc) (0.28.0)
Requirement already satisfied: webdriver-manager in c:\users\twilcox\zephyrproject\.venv\lib\site-packages (from strictdoc) (4.0.1)
Requirement already satisfied: websockets in c:\users\twilcox\zephyrproject\.venv\lib\site-packages (from strictdoc) (12.0)
Requirement already satisfied: xlrd==2.*,>=2.0.1 in c:\users\twilcox\zephyrproject\.venv\lib\site-packages (from strictdoc) (2.0.1)
Requirement already satisfied: xlsxwriter==1.*,>=1.3.7 in c:\users\twilcox\zephyrproject\.venv\lib\site-packages (from strictdoc) (1.4.5)
Requirement already satisfied: soupsieve>1.2 in c:\users\twilcox\zephyrproject\.venv\lib\site-packages (from beautifulsoup4==4.*,>=4.12.0->strictdoc) (2.5)
Requirement already satisfied: PyYAML>=3.01 in c:\users\twilcox\zephyrproject\.venv\lib\site-packages (from pybtex==0.*,>=0.23.0->strictdoc) (6.0.1)
Requirement already satisfied: latexcodec>=1.0.4 in c:\users\twilcox\zephyrproject\.venv\lib\site-packages (from pybtex==0.*,>=0.23.0->strictdoc) (3.0.0)
Requirement already satisfied: six in c:\users\twilcox\zephyrproject\.venv\lib\site-packages (from pybtex==0.*,>=0.23.0->strictdoc) (1.16.0)
Requirement already satisfied: xmlschema>=2.4.0 in c:\users\twilcox\zephyrproject\.venv\lib\site-packages (from reqif==0.*,>=0.0.39->strictdoc) (3.0.2)
Requirement already satisfied: Arpeggio>=2.0.0 in c:\users\twilcox\zephyrproject\.venv\lib\site-packages (from textx==3.*,>=3.0.0->strictdoc) (2.0.2)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,!=2.1.0,<3.0.0,>=1.7.4 in c:\users\twilcox\zephyrproject\.venv\lib\site-packages (from fastapi>=0.83.0->strictdoc) (2.6.4)
Requirement already satisfied: starlette<0.37.0,>=0.36.3 in c:\users\twilcox\zephyrproject\.venv\lib\site-packages (from fastapi>=0.83.0->strictdoc) (0.36.3)
Requirement already satisfied: typing-extensions>=4.8.0 in c:\users\twilcox\zephyrproject\.venv\lib\site-packages (from fastapi>=0.83.0->strictdoc) (4.10.0)
Requirement already satisfied: webencodings in c:\users\twilcox\zephyrproject\.venv\lib\site-packages (from html5lib>=1.1->strictdoc) (0.5.1)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\twilcox\zephyrproject\.venv\lib\site-packages (from jinja2>=2.11.2->strictdoc) (2.1.5)
Requirement already satisfied: click>=7.0 in c:\users\twilcox\zephyrproject\.venv\lib\site-packages (from uvicorn>=0.14.0->uvicorn[standard]>=0.14.0->strictdoc) (8.1.3)
Requirement already satisfied: h11>=0.8 in c:\users\twilcox\zephyrproject\.venv\lib\site-packages (from uvicorn>=0.14.0->uvicorn[standard]>=0.14.0->strictdoc) (0.14.0)
Requirement already satisfied: colorama>=0.4 in c:\users\twilcox\zephyrproject\.venv\lib\site-packages (from uvicorn[standard]>=0.14.0->strictdoc) (0.4.6)
Requirement already satisfied: httptools>=0.5.0 in c:\users\twilcox\zephyrproject\.venv\lib\site-packages (from uvicorn[standard]>=0.14.0->strictdoc) (0.6.1)
Requirement already satisfied: python-dotenv>=0.13 in c:\users\twilcox\zephyrproject\.venv\lib\site-packages (from uvicorn[standard]>=0.14.0->strictdoc) (1.0.1)
Requirement already satisfied: watchfiles>=0.13 in c:\users\twilcox\zephyrproject\.venv\lib\site-packages (from uvicorn[standard]>=0.14.0->strictdoc) (0.21.0)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\twilcox\zephyrproject\.venv\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium->strictdoc) (2.2.1)
Requirement already satisfied: trio~=0.17 in c:\users\twilcox\zephyrproject\.venv\lib\site-packages (from selenium->strictdoc) (0.24.0)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\twilcox\zephyrproject\.venv\lib\site-packages (from selenium->strictdoc) (0.11.1)
Requirement already satisfied: certifi>=2021.10.8 in c:\users\twilcox\zephyrproject\.venv\lib\site-packages (from selenium->strictdoc) (2024.2.2)
Requirement already satisfied: xmltodict in c:\users\twilcox\zephyrproject\.venv\lib\site-packages (from spdx-tools->strictdoc) (0.13.0)
Requirement already satisfied: rdflib in c:\users\twilcox\zephyrproject\.venv\lib\site-packages (from spdx-tools->strictdoc) (7.0.0)
Requirement already satisfied: beartype in c:\users\twilcox\zephyrproject\.venv\lib\site-packages (from spdx-tools->strictdoc) (0.17.2)
Requirement already satisfied: uritools in c:\users\twilcox\zephyrproject\.venv\lib\site-packages (from spdx-tools->strictdoc) (4.0.2)
Requirement already satisfied: license-expression in c:\users\twilcox\zephyrproject\.venv\lib\site-packages (from spdx-tools->strictdoc) (30.2.0)
Requirement already satisfied: ply in c:\users\twilcox\zephyrproject\.venv\lib\site-packages (from spdx-tools->strictdoc) (3.11)
Requirement already satisfied: semantic-version in c:\users\twilcox\zephyrproject\.venv\lib\site-packages (from spdx-tools->strictdoc) (2.10.0)
Requirement already satisfied: requests in c:\users\twilcox\zephyrproject\.venv\lib\site-packages (from webdriver-manager->strictdoc) (2.31.0)
Requirement already satisfied: packaging in c:\users\twilcox\zephyrproject\.venv\lib\site-packages (from webdriver-manager->strictdoc) (23.2)
Requirement already satisfied: annotated-types>=0.4.0 in c:\users\twilcox\zephyrproject\.venv\lib\site-packages (from pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,!=2.1.0,<3.0.0,>=1.7.4->fastapi>=0.83.0->strictdoc) (0.6.0)
Requirement already satisfied: pydantic-core==2.16.3 in c:\users\twilcox\zephyrproject\.venv\lib\site-packages (from pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,!=2.1.0,<3.0.0,>=1.7.4->fastapi>=0.83.0->strictdoc) (2.16.3)
Requirement already satisfied: anyio<5,>=3.4.0 in c:\users\twilcox\zephyrproject\.venv\lib\site-packages (from starlette<0.37.0,>=0.36.3->fastapi>=0.83.0->strictdoc) (4.3.0)
Requirement already satisfied: attrs>=20.1.0 in c:\users\twilcox\zephyrproject\.venv\lib\site-packages (from trio~=0.17->selenium->strictdoc) (23.2.0)
Requirement already satisfied: sortedcontainers in c:\users\twilcox\zephyrproject\.venv\lib\site-packages (from trio~=0.17->selenium->strictdoc) (2.4.0)
Requirement already satisfied: idna in c:\users\twilcox\zephyrproject\.venv\lib\site-packages (from trio~=0.17->selenium->strictdoc) (3.6)
Requirement already satisfied: outcome in c:\users\twilcox\zephyrproject\.venv\lib\site-packages (from trio~=0.17->selenium->strictdoc) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in c:\users\twilcox\zephyrproject\.venv\lib\site-packages (from trio~=0.17->selenium->strictdoc) (1.3.1)
Requirement already satisfied: cffi>=1.14 in c:\users\twilcox\zephyrproject\.venv\lib\site-packages (from trio~=0.17->selenium->strictdoc) (1.16.0)
Requirement already satisfied: exceptiongroup in c:\users\twilcox\zephyrproject\.venv\lib\site-packages (from trio~=0.17->selenium->strictdoc) (1.2.0)
Requirement already satisfied: wsproto>=0.14 in c:\users\twilcox\zephyrproject\.venv\lib\site-packages (from trio-websocket~=0.9->selenium->strictdoc) (1.2.0)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in c:\users\twilcox\zephyrproject\.venv\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium->strictdoc) (1.7.1)
Requirement already satisfied: elementpath<5.0.0,>=4.3.0 in c:\users\twilcox\zephyrproject\.venv\lib\site-packages (from xmlschema>=2.4.0->reqif==0.*,>=0.0.39->strictdoc) (4.4.0)
Requirement already satisfied: boolean.py>=4.0 in c:\users\twilcox\zephyrproject\.venv\lib\site-packages (from license-expression->spdx-tools->strictdoc) (4.0)
Requirement already satisfied: isodate<0.7.0,>=0.6.0 in c:\users\twilcox\zephyrproject\.venv\lib\site-packages (from rdflib->spdx-tools->strictdoc) (0.6.1)
Requirement already satisfied: pyparsing<4,>=2.1.0 in c:\users\twilcox\zephyrproject\.venv\lib\site-packages (from rdflib->spdx-tools->strictdoc) (3.1.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\twilcox\zephyrproject\.venv\lib\site-packages (from requests->webdriver-manager->strictdoc) (3.3.2)
Requirement already satisfied: pycparser in c:\users\twilcox\zephyrproject\.venv\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium->strictdoc) (2.21)_

**Comment by stanislaw** [comment] 2024-03-13 20:22
Could you run `pip install strictdoc --pre` one more time? Sometimes it takes some time for a new package to come up. You should see it under version 0.0.50a.

**Comment by Timotheous** [comment] 2024-03-13 20:25
Seems I got 0.0.49 again.
_Requirement already satisfied: strictdoc in c:\users\twilcox\zephyrproject\.venv\lib\site-packages (0.0.49)_

I am on a VPN into the office.  Let me disable it and try again.

**Comment by stanislaw** [comment] 2024-03-13 20:26
```
strictdoc-project/strictdoc (fragments2) $ pip install strictdoc --pre
Collecting strictdoc
  Downloading strictdoc-0.0.50a1.tar.gz (6.0 MB)
  ...
```

This can be some caches and differences between regions.

**Comment by Timotheous** [comment] 2024-03-13 20:32
Then it could just need some time. 
I will try again in a few hours. 

If that does not work we can take it up tomorrow.

**Comment by stanislaw** [comment] 2024-03-13 20:33
Sounds good. Let me know when you have it run again.

**Comment by stanislaw** [comment] 2024-03-15 20:16
I have merged the venv-related fix because it should be a step forward anyway. Please let me know if the issue is fixed for you. If not, please reopen.

**Closed** 2024-03-15 20:15 UTC
Labels: Bug, Core roadmap
