### ISSUE TITLE
Recursive copying of the assets shall be limited to a known set of folders

### ISSUE THREAD

**Issue by stanislaw** [strictdoc-project/strictdoc#1472] opened 2023-11-19 09:30 UTC
```
...
Copying project assets "strictdoc/strictdoc-project.github.io/strictdoc/strictdoc-project.github.io/strictdoc/strictdoc-project.github.io/strictdoc/docs/sphinx/source/_assets": 2 files.
Copying project assets "strictdoc/strictdoc-project.github.io/strictdoc/strictdoc-project.github.io/strictdoc/docs/_assets": 2 files.
...
```

**Comment by mettta** [comment] 2023-12-27 19:09
It is a duplicate of #1369.

**Closed by mettta** 2023-12-27 19:09 UTC
Labels: Bug, Second roadmap
