### ISSUE TITLE
MathJax fonts not always synced

### ISSUE THREAD

**Issue by lochsh** [strictdoc-project/strictdoc#723] opened 2022-06-22 14:49 UTC
For some reason, the MathJax fonts in `strictdoc/export/html/_static_extra/mathjax/output/chtml/fonts/woff-v2/` are not always synced with the output directory`/_static/...`. (When `--enable-mathjax` is set, of course.)

I think it might be a cache invalidation issue stemming from using https://docs.python.org/3/distutils/apiref.html#distutils.dir_util.copy_tree with `update=True`.

I'll see if I can get some reliable reproductions of this and will update the issue.

**Comment by stanislaw** [comment] 2022-11-27 10:38
Due to Python 3.11 compatibility, I had to change the implementation to use shutils-based copytree, see https://github.com/strictdoc-project/strictdoc/pull/734 and adapt it to the incremental copying. I don't know if this has an effect on your issue but I would suggest that we close it for now until you have a specific reproducible example.

The MathJax is exercised by the integration tests: tests/integration/commands/export/html/mathjax.

The new copytree function can be found here: `strictdoc/helpers/file_system.py`.

**Closed by stanislaw** 2022-11-27 10:38 UTC
